# Generated by Django 4.2.7 on 2025-01-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_app', '0003_update_active_round_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='profile_image',
            field=models.ImageField(blank=True, default='defaults/people.svg', null=True, upload_to='participant_profiles/'),
        ),
    ]
