# Generated by Django 4.2.7 on 2025-01-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_app', '0004_participant_gender_alter_participant_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], default='PREFER_NOT_TO_SAY', max_length=20),
        ),
    ]
