# Generated by Django 4.2.7 on 2025-01-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_app', '0005_alter_participant_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='prefer_not_to_say', max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='participant_profiles/'),
        ),
    ]
