# Generated by Django 5.1.2 on 2025-03-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_app', '0007_alter_participant_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionresult',
            name='tiebreaker_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
